version: '3.4'

services:
  walmart.api.product:
    image: walmartapiproduct:dev
    container_name: Walmart.Api.Product
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Walmart.Api.Product"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_walmart.api.product$
    volumes:
      - C:\Proyectos\WalmartChallengeBackEnd\Walmart.Api.Product:/app
      - C:\Proyectos\WalmartChallengeBackEnd:/src
      - C:\Users\ACL\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_walmart.api.product$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_walmart.api.product$ \"/app/bin/Debug/netcoreapp3.1/Walmart.Api.Product.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true